# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    includeNuGetOrg: true
- task: MSBuild@1
  inputs:
    configuration: $(buildConfiguration)
- script: |
    dotnet test ./src/CSharpToPython.Tests/CSharpToPython.Tests.csproj
  displayName: 'dotnet test $(buildConfiguration)'
  failOnStderr: true
- task: CopyFiles@2
  inputs:
    sourceFolder: 'src\CSharpToPython.Web\bin\$(buildConfiguration)\netstandard2.0\'
    contents: 'dist\**'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: CopyFiles@2
  inputs:
    contents: 'DeployToGhPages.ps1'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: BuildOutputs
